wdir="/home/pkaran/Samsung/data/MT_Diffusion/myelo_inferno";
# wdir="/home/local/USHERBROOKE/karp2601/Samsung/data/MT_Diffusion/myelo_inferno";
# wdir="/home/local/USHERBROOKE/karp2601/data/stockage/MT_Diffusion/myelo_inferno";
source_dir="source";
# source_dir="Research/source";
types=("intra_subject_w_b1" "inter_subject_w_b1");
measures=("MTR" "MTsat" "ihMTR" "ihMTsat");
nb_bundles=("few" "all");
stats=("correlation" "variation")
for type in "${types[@]}";
    do echo $type;
    cd ${wdir}/$type/characterization/bundles_5deg_bins;
    all_subs=(sub-0*);
    for measure in "${measures[@]}";
        do echo $measure;
        for nb_bundle in "${nb_bundles[@]}";
            do echo $nb_bundle;
            for stat in "${stats[@]}";
                do echo $stat;
                python ~/$source_dir/MRM_characterization/scripts/visualize_stats.py stats/ --in_stats */stats/${measure}_${nb_bundle}_bundles_${stat}.txt --mean --suffix ${nb_bundle}_bundles;
            done;
        done;
    done;
done;